// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC2rLhO93K0faARaiKzL3G80AilKLe-wU',
    appId: '1:426378925787:web:69710ff1b23c6087b09efe',
    messagingSenderId: '426378925787',
    projectId: 'learningapp-5ef0e',
    authDomain: 'learningapp-5ef0e.firebaseapp.com',
    storageBucket: 'learningapp-5ef0e.appspot.com',
    measurementId: 'G-MNYNTXGZSL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkjS3AtOnqpna6uhhHmNDQftGlRdEd3ng',
    appId: '1:426378925787:android:732d610e88aab1e5b09efe',
    messagingSenderId: '426378925787',
    projectId: 'learningapp-5ef0e',
    storageBucket: 'learningapp-5ef0e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0IaE943c2CGHWO8ayfmaQ8U-7VKd-ems',
    appId: '1:426378925787:ios:e8c077044bc92bfdb09efe',
    messagingSenderId: '426378925787',
    projectId: 'learningapp-5ef0e',
    storageBucket: 'learningapp-5ef0e.appspot.com',
    iosBundleId: 'com.example.learningApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0IaE943c2CGHWO8ayfmaQ8U-7VKd-ems',
    appId: '1:426378925787:ios:2542f386a0f44663b09efe',
    messagingSenderId: '426378925787',
    projectId: 'learningapp-5ef0e',
    storageBucket: 'learningapp-5ef0e.appspot.com',
    iosBundleId: 'com.example.learningApp.RunnerTests',
  );
}
